---
validate_vertices: false
clear_distant_blocks: true
dense_representation_radius_m: 8.0
voxels_per_side: 16
voxel_size: 0.1
num_poses_per_update: 1
max_input_queue_size: 0
pointcloud_separation_s: 0.2
tf_wait_duration_s: 0.1
mesh:
  use_color: true
  min_weight: 0.0001
  integrator_threads: -1
tsdf:
  voxel_carving_enabled: true
  use_const_weight: false
  default_truncation_distance: 0.2
  max_weight: 10000
  min_ray_length_m: 0.1
  max_ray_length_m: 4.5
  allow_clear: true
  use_weight_dropoff: true
  use_sparsity_compensation_factor: false
  integration_order_mode: mixed
  enable_anti_grazing: false
  start_voxel_subsampling_factor: 2
  max_consecutive_ray_collisions: 2
  clear_checks_every_n_frames: 1
  integrator_threads: -1
