---
semantic_measurement_probability: 0.7
total_semantic_labels: 150
dynamic_labels: [12, 126]
invalid_labels: []
objects:
  labels:
    - 4
    - 7
    - 10
    - 15
    - 17
    - 18
    - 19
    - 20
    - 22
    - 23
    - 24
    - 27
    - 28
    - 30
    - 31
    - 33
    - 35
    - 36
    - 37
    - 39
    - 41
    - 43
    - 44
    - 47
    - 49
    - 50
    - 55
    - 57
    - 58
    - 62
    - 64
    - 65
    - 66
    - 67
    - 69
    - 71
    - 72
    - 74
    - 75
    - 76
    - 80
    - 81
    - 82
    - 83
    - 85
    - 87
    - 89
    - 92
    - 97
    - 98
    - 100
    - 102
    - 103
    - 104
    - 107
    - 108
    - 110
    - 111
    - 112
    - 114
    - 115
    - 116
    - 117
    - 118
    - 119
    - 120
    - 124
    - 125
    - 127
    - 129
    - 130
    - 131
    - 132
    - 135
    - 137
    - 138
    - 139
    - 141
    - 142
    - 143
    - 144
    - 146
    - 147
    - 148
    - 149
label_names:
  - {label: 0, name: wall}
  - {label: 1, name: building}
  - {label: 2, name: sky}
  - {label: 3, name: floor}
  - {label: 4, name: tree}
  - {label: 5, name: ceiling}
  - {label: 6, name: road}
  - {label: 7, name: bed}
  - {label: 8, name: windowpane}
  - {label: 9, name: grass}
  - {label: 10, name: cabinet}
  - {label: 11, name: sidewalk}
  - {label: 12, name: person}
  - {label: 13, name: earth}
  - {label: 14, name: door}
  - {label: 15, name: table}
  - {label: 16, name: mountain}
  - {label: 17, name: plant}
  - {label: 18, name: curtain}
  - {label: 19, name: chair}
  - {label: 20, name: car}
  - {label: 21, name: water}
  - {label: 22, name: painting}
  - {label: 23, name: sofa}
  - {label: 24, name: shelf}
  - {label: 25, name: house}
  - {label: 26, name: sea}
  - {label: 27, name: mirror}
  - {label: 28, name: rug}
  - {label: 29, name: field}
  - {label: 30, name: armchair}
  - {label: 31, name: seat}
  - {label: 32, name: fence}
  - {label: 33, name: desk}
  - {label: 34, name: rock}
  - {label: 35, name: wardrobe}
  - {label: 36, name: lamp}
  - {label: 37, name: bathtub}
  - {label: 38, name: railing}
  - {label: 39, name: cushion}
  - {label: 40, name: base}
  - {label: 41, name: box}
  - {label: 42, name: column}
  - {label: 43, name: signboard}
  - {label: 44, name: chest}
  - {label: 45, name: counter}
  - {label: 46, name: sand}
  - {label: 47, name: sink}
  - {label: 48, name: skyscraper}
  - {label: 49, name: fireplace}
  - {label: 50, name: refrigerator}
  - {label: 51, name: grandstand}
  - {label: 52, name: path}
  - {label: 53, name: stairs}
  - {label: 54, name: runway}
  - {label: 55, name: case}
  - {label: 56, name: pool}
  - {label: 57, name: pillow}
  - {label: 58, name: screen}
  - {label: 59, name: stairway}
  - {label: 60, name: river}
  - {label: 61, name: bridge}
  - {label: 62, name: bookcase}
  - {label: 63, name: blind}
  - {label: 64, name: coffee}
  - {label: 65, name: toilet}
  - {label: 66, name: flower}
  - {label: 67, name: book}
  - {label: 68, name: hill}
  - {label: 69, name: bench}
  - {label: 70, name: countertop}
  - {label: 71, name: stove}
  - {label: 72, name: palm}
  - {label: 73, name: kitchen}
  - {label: 74, name: computer}
  - {label: 75, name: swivel}
  - {label: 76, name: boat}
  - {label: 77, name: bar}
  - {label: 78, name: arcade}
  - {label: 79, name: hovel}
  - {label: 80, name: bus}
  - {label: 81, name: towel}
  - {label: 82, name: light}
  - {label: 83, name: truck}
  - {label: 84, name: tower}
  - {label: 85, name: chandelier}
  - {label: 86, name: awning}
  - {label: 87, name: streetlight}
  - {label: 88, name: booth}
  - {label: 89, name: television}
  - {label: 90, name: airplane}
  - {label: 91, name: dirt}
  - {label: 92, name: apparel}
  - {label: 93, name: pole}
  - {label: 94, name: land}
  - {label: 95, name: bannister}
  - {label: 96, name: escalator}
  - {label: 97, name: ottoman}
  - {label: 98, name: bottle}
  - {label: 99, name: buffet}
  - {label: 100, name: poster}
  - {label: 101, name: stage}
  - {label: 102, name: van}
  - {label: 103, name: ship}
  - {label: 104, name: fountain}
  - {label: 105, name: conveyer}
  - {label: 106, name: canopy}
  - {label: 107, name: washer}
  - {label: 108, name: plaything}
  - {label: 109, name: swimming}
  - {label: 110, name: stool}
  - {label: 111, name: barrel}
  - {label: 112, name: basket}
  - {label: 113, name: waterfall}
  - {label: 114, name: tent}
  - {label: 115, name: bag}
  - {label: 116, name: minibike}
  - {label: 117, name: cradle}
  - {label: 118, name: oven}
  - {label: 119, name: ball}
  - {label: 120, name: food}
  - {label: 121, name: step}
  - {label: 122, name: tank}
  - {label: 123, name: trade}
  - {label: 124, name: microwave}
  - {label: 125, name: pot}
  - {label: 126, name: animal}
  - {label: 127, name: bicycle}
  - {label: 128, name: lake}
  - {label: 129, name: dishwasher}
  - {label: 130, name: screen}
  - {label: 131, name: blanket}
  - {label: 132, name: sculpture}
  - {label: 133, name: hood}
  - {label: 134, name: sconce}
  - {label: 135, name: vase}
  - {label: 136, name: traffic}
  - {label: 137, name: tray}
  - {label: 138, name: ashcan}
  - {label: 139, name: fan}
  - {label: 140, name: pier}
  - {label: 141, name: crt}
  - {label: 142, name: plate}
  - {label: 143, name: monitor}
  - {label: 144, name: bulletin}
  - {label: 145, name: shower}
  - {label: 146, name: radiator}
  - {label: 147, name: glass}
  - {label: 148, name: clock}
  - {label: 149, name: flag}
